### ISSUE TITLE
Error while composing: unrecognized subdirective handle_errors, at /etc/caddy/Caddyfile:12

### ISSUE THREAD

**Issue by R-Bose** [bannert1337/ollama-wol-proxy#1]
```log
ollama-wol-proxy-1  | Error: adapting config using caddyfile: parsing caddyfile tokens for 'handle': parsing caddyfile tokens for 'reverse_proxy': unrecognized subdirective handle_errors, at /etc/caddy/Caddyfile:12 import chain ['/etc/caddy/Caddyfile:50 (import common)'], at /etc/caddy/Caddyfile:22 import chain ['/etc/caddy/Caddyfile:50 (import common)']
```

I had to modify the setup a bit because it didn't work out of box, so managed to create a docker-compose that uses the Dockerfile in the repo:

````yaml
services:
  ollama-wol-proxy:
    image: ollama-wol-proxy
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./Caddyfile:/etc/caddy/Caddyfile"
    ports:
      - "11434:11434"
    network_mode: host
    restart: always
````
No diff in Caddyfile, so I presume something went wrong with the caddy version being used?

I investigated [caddy-wol](github.com/dulli/caddy-wol) and they don't use the dockerfile the same way you did and I suspect it might have to do something with Caddy V1 vs V2. Could you look into the error?

System Info (if relevant):
MacOS 15.4.1
Docker version 27.5.1, build 9f9e405
